- hosts: postgresqlservers
  remote_user: root
  tasks:
    - name: update apt cache 
      apt: update_cache=yes cache_valid_time=3600      
  roles:
    - roles/Ansibles.build-essential
    - roles/Ansibles.postgresql